import type { RoomContent, RoomPuzzle } from '../types';

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'puzzleflow-room';
}

function asList(value: string[] | string | undefined): string[] {
  if (!value) return [];
  return Array.isArray(value) ? value : [value];
}

export function getRoomPuzzles(room: RoomContent): RoomPuzzle[] {
  if (room.puzzle_flow?.length) return room.puzzle_flow;

  return (room.puzzles || []).map((puzzle, index) => ({
    title: puzzle.name,
    role_in_flow: index === 0 ? 'Opening puzzle' : 'Linked puzzle',
    estimated_time: 'Not specified',
    required_props: puzzle.props,
    setup: puzzle.setup,
    player_facing_clue: 'See setup notes.',
    hint_ladder: [],
    solution: puzzle.solution,
    output: puzzle.output,
    reset_notes: 'Reset according to operator notes.',
    safety_or_ops_notes: 'No additional notes supplied.',
  }));
}

export function getRoomExportFileName(room: RoomContent, extension: 'md' | 'json'): string {
  return `${slugify(room.title)}.${extension}`;
}

export function downloadTextFile(fileName: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function pushSection(lines: string[], title: string, body?: string | string[]): void {
  const items = asList(body);
  if (!items.length) return;
  lines.push('', `## ${title}`, '');
  if (items.length === 1) {
    lines.push(items[0]);
    return;
  }
  items.forEach((item) => lines.push(`- ${item}`));
}

export function roomToMarkdown(room: RoomContent): string {
  const puzzles = getRoomPuzzles(room);
  const redHerrings = room.red_herrings || room.redHerrings || [];
  const lines: string[] = [`# ${room.title}`, ''];

  if (room.tagline) lines.push(`_${room.tagline}_`, '');
  lines.push('| Field | Value |');
  lines.push('|---|---|');
  lines.push(`| Theme | ${room.theme || 'Not specified'} |`);
  lines.push(`| Difficulty | ${room.difficulty || 'Not specified'} |`);
  lines.push(`| Players | ${room.players || 'Not specified'} |`);
  lines.push(`| Duration | ${room.duration || 'Not specified'} |`);
  lines.push(`| Format | ${room.format || 'Not specified'} |`);

  pushSection(lines, 'Operator Summary', room.operator_summary);

  if (room.story || room.narrative) {
    lines.push('', '## Story', '');
    if (room.story) {
      lines.push(`### Introduction\n${room.story.introduction}`);
      lines.push(`\n### Midpoint\n${room.story.midpoint}`);
      lines.push(`\n### Climax\n${room.story.climax}`);
      lines.push(`\n### Resolution\n${room.story.resolution}`);
    } else if (room.narrative) {
      lines.push(`### Introduction\n${room.narrative.intro}`);
      lines.push(`\n### Climax\n${room.narrative.climax}`);
      lines.push(`\n### Resolution\n${room.narrative.outro}`);
    }
  }

  lines.push('', '## Puzzle Flow', '');
  puzzles.forEach((puzzle, index) => {
    lines.push(`### ${index + 1}. ${puzzle.title}`, '');
    lines.push(`**Role in flow:** ${puzzle.role_in_flow}`);
    lines.push(`**Estimated time:** ${puzzle.estimated_time}`);
    lines.push('', '**Required props:**');
    puzzle.required_props.forEach((prop) => lines.push(`- ${prop}`));
    lines.push('', `**Setup:** ${puzzle.setup}`);
    lines.push('', `**Player-facing clue:** ${puzzle.player_facing_clue}`);
    if (puzzle.hint_ladder.length) {
      lines.push('', '**Hint ladder:**');
      puzzle.hint_ladder.forEach((hint, hintIndex) => lines.push(`${hintIndex + 1}. ${hint}`));
    }
    lines.push('', `**Solution:** ${puzzle.solution}`);
    lines.push('', `**Output:** ${puzzle.output}`);
    lines.push('', `**Reset notes:** ${puzzle.reset_notes}`);
    lines.push('', `**Safety/Ops notes:** ${puzzle.safety_or_ops_notes}`, '');
  });

  pushSection(lines, 'Red Herrings', redHerrings);
  pushSection(lines, 'Production Notes', room.production_notes);
  pushSection(lines, 'Shopping List', room.shopping_list);
  pushSection(lines, 'Staffing Notes', room.staffing_notes);
  pushSection(lines, 'Reset Checklist', room.reset_checklist);
  pushSection(lines, 'Accessibility Notes', room.accessibility_notes);

  lines.push('', '---', 'Generated by PuzzleFlow AI.');
  return `${lines.join('\n')}\n`;
}

export function downloadRoomMarkdown(room: RoomContent): void {
  downloadTextFile(getRoomExportFileName(room, 'md'), roomToMarkdown(room), 'text/markdown;charset=utf-8');
}

export function downloadRoomJson(room: RoomContent): void {
  downloadTextFile(getRoomExportFileName(room, 'json'), `${JSON.stringify(room, null, 2)}\n`, 'application/json;charset=utf-8');
}

export async function copyOperatorSummary(room: RoomContent): Promise<void> {
  const summary = room.operator_summary || room.tagline || room.title;
  await navigator.clipboard.writeText(summary);
}
